### ISSUE TITLE
内部不是vue3 写法

### ISSUE THREAD

**Issue by lixiaofa** [edram/vant-next-sku#7]
内部好像还是vue2的写法， 有后续计划到vue 3吗？
@EmiyaGm @edram

**Comment by edram** [comment]
vue 的版本是 v3， sku 组件是参考 vant 2 迁移过来的

**Comment by lixiaofa** [comment]
> 



> vue 的版本是 v3， sku 组件是参考 vant 2 迁移过来的

我试着迁移了一下， 比较吃力 。能指导一下吗，谢谢

@EmiyaGm @edram

**Comment by edram** [comment]
加我微信 28820490 @lixiaofa
